image: node:12.16.3

stages:
  - build
  - test
  - production

build:
  stage: build
  script:
    - npm install --dev
    - npm run build

test basic:
  stage: test
  script:
    - npm install --dev
    - npm run test-basic

test database:
  stage: test
  script:
    - npm install --dev
    - npm run test-db

production:
  type: deploy
  stage: production
  image: line5/drp-backend:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
    - pipeline