image: node:12.16.3

stages:
  - build
  - test
  - production

build:
  stage: build
  script:
    - npm install
    - npm run build
test:
  stage: test
  script:
    - npm install
    - npm run test

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master