image: node:latest

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  path:
    - .npm/

stages:
  - build
  - test
  - deploy

before_script:
  - npm ci --cache .npm

build:
  stage: build
  cache:
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - .dist/

test basic:
  stage: test
  cache:
    policy: pull
  script:
    - npm run test-basic
  dependencies: []
  except:
    - staging

test database:
  stage: test
  cache:
    policy: pull
  script:
    - npm run test-postgres
  dependencies: []
  except:
    - staging

test aws:
  stage: test
  cache:
    policy: pull
  script:
    - npm run test-aws
  dependencies: []
  except:
    - staging

staging:
  stage: deploy
  image: line5/drp-backend:latest
  cache: {}
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY --skip_cleanup=true
  only:
    - master
    - staging

production:
  stage: deploy
  image: line5/drp-backend:latest
  cache: {}
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --skip_cleanup=true
  only:
    - master